wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1668349847.58546
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.7
      5: 0.13.4
      8:
      - 1
      - 2
      - 3
      - 5
